parameters:
  timeoutInMinutes: 5
steps:
  - task: Kubernetes@1
    displayName: Configure cluster
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    condition: and(succeeded(), not(eq(variables.configure_cluster, false)))
    inputs:
      command: login
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: $(kubernetesServiceConnection)